### ISSUE TITLE
Unable to connect to neo4j 4.0.6. Internal server error:500

### ISSUE THREAD

**Issue by ysruthi** [ArcadeData/arcadeanalytics-recipes#3]
Hi,

I have tried using docker recipes from this repo and the arcadeanalytics/src/main/docker and with both these recipes when I try to connect to a Neo4J instance running in a container I get the following error:
When i try using SSH tunnel, I get the following error indicating that there is a private key mismatch. 

`
arcadeanalytics-single_1  | 2020-06-24 21:35:55.777  INFO 1 --- [ XNIO-2 task-26] c.a.web.rest.DataSourceResource          : REST request to test DataSource : DataSourceDTO{id=1251, name='test', description='test', type='NEO4J', indexing='NOT_INDEXED', server='arcadeanalytics-neo4j', port=7678, database='NONE', username='neo4j', password='neo1', remote='true', gateway='192.168.1.212', sshPort=22, sshUser='hidden'}
arcadeanalytics-single_1  | 2020-06-24 21:35:55.778  INFO 1 --- [ XNIO-2 task-26] c.a.web.rest.DataSourceResource          : DataSource : DataSource{id=1251, name='test', description='test', type='NEO4J', indexing='NOT_INDEXED', server='arcadeanalytics-neo4j', port=7678, database='NONE', username='neo4j', password='neo1', remote='true', gateway='192.168.1.212', sshPort=22, sshUser='hidden'}
arcadeanalytics-single_1  | 2020-06-24 21:35:55.797 ERROR 1 --- [ XNIO-2 task-26] o.z.p.spring.web.advice.AdviceTrait      : Internal Server Error
arcadeanalytics-single_1  |
arcadeanalytics-single_1  | java.lang.RuntimeException: com.arcadeanalytics.connectors.base.com.jcraft.jsch.JSchException: invalid privatekey: [B@5292f9ae
arcadeanalytics-single_1  | 	at com.arcadeanalytics.provider.SshTunnelTemplate.buildTunnel(SshTunnelTemplate.kt:69)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.provider.SshTunnelDataProviderDecorator.testConnection(SshTunnelDataProviderDecorator.kt:32)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.web.rest.DataSourceResource.testDataSource(DataSourceResource.java:143)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.web.rest.DataSourceResource$$FastClassBySpringCGLIB$$89a9850e.invoke(<generated>)
arcadeanalytics-single_1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
arcadeanalytics-single_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
arcadeanalytics-single_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
arcadeanalytics-single_1  | 	at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:48)
arcadeanalytics-single_1  | 	at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:34)
arcadeanalytics-single_1  | 	at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
arcadeanalytics-single_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
arcadeanalytics-single_1  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.web.rest.DataSourceResource$$EnhancerBySpringCGLIB$$c38f46ac.testDataSource(<generated>)
arcadeanalytics-single_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
arcadeanalytics-single_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
arcadeanalytics-single_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arcadeanalytics-single_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
arcadeanalytics-single_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
arcadeanalytics-single_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
`

`
docker-compose -f app-single.yml ps
             Name                            Command               State                                  Ports
-----------------------------------------------------------------------------------------------------------------------------------------------
docker_arcadeanalytics-neo4j_1    /sbin/tini -g -- /docker-e ...   Up      0.0.0.0:7473->7473/tcp, 0.0.0.0:7474->7474/tcp,
                                                                           0.0.0.0:7687->7687/tcp
docker_arcadeanalytics-single_1   /bin/sh -c echo "The appli ...   Up      0.0.0.0:8080->8080/tcp
`

Although, I am able to exec to the arcadeanalytics container and ping the 'arcadeanalytics-neo4j' container and am also able to SSH using the keys installed on the container:

`
sudo docker exec -it docker_arcadeanalytics-single_1 /bin/sh
/ # ssh hidden@192.168.1.212 -i arcade/.ssh/id_rsa
The authenticity of host '192.168.1.212 (192.168.1.212)' can't be established.
ECDSA key fingerprint is SHA256:57Jbfm4KBjY2CbKIeUASPtDbOlQ/7e6L0W/Ngy1lfdE.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.1.212' (ECDSA) to the list of known hosts.
Last login: Wed Jun 24 17:03:41 2020 from 192.168.1.212

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
`

When I run without SSH, I get an error indicating that it cannot locate the database server:
`
arcadeanalytics-single_1  | 2020-06-24 21:32:48.388  INFO 1 --- [ XNIO-2 task-12] c.a.web.rest.DataSourceResource          : REST request to test DataSource : DataSourceDTO{id=1251, name='test', description='test', type='NEO4J', indexing='NOT_INDEXED', server='arcadeanalytics-neo4j', port=7678, database='NONE', username='neo4j', password='neo1', remote='false', gateway='192.168.1.212', sshPort=22, sshUser='hidden'}
arcadeanalytics-single_1  | 2020-06-24 21:32:48.391  INFO 1 --- [ XNIO-2 task-12] c.a.web.rest.DataSourceResource          : DataSource : DataSource{id=1251, name='test', description='test', type='NEO4J', indexing='NOT_INDEXED', server='arcadeanalytics-neo4j', port=7678, database='NONE', username='neo4j', password='neo1', remote='false', gateway='192.168.1.212', sshPort=22, sshUser='hidden'}
arcadeanalytics-single_1  | 2020-06-24 21:32:49.023  INFO 1 --- [ XNIO-2 task-12] Driver                                   : Direct driver instance 713221148 created for server address arcadeanalytics-neo4j:7678
arcadeanalytics-single_1  | 2020-06-24 21:32:49.621  INFO 1 --- [ XNIO-2 task-12] ConnectionPool                           : Closing connection pool towards arcadeanalytics-neo4j:7678
arcadeanalytics-single_1  | 2020-06-24 21:32:51.851 ERROR 1 --- [ XNIO-2 task-12] o.z.p.spring.web.advice.AdviceTrait      : Internal Server Error
arcadeanalytics-single_1  |
arcadeanalytics-single_1  | org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Unable to connect to arcadeanalytics-neo4j:7678, ensure the database is running and that there is a working network connection to it.
arcadeanalytics-single_1  | 	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:122)
arcadeanalytics-single_1  | 	at org.neo4j.driver.internal.DriverFactory.verifyConnectivity(DriverFactory.java:346)
arcadeanalytics-single_1  | 	at org.neo4j.driver.internal.DriverFactory.newInstance(DriverFactory.java:93)
arcadeanalytics-single_1  | 	at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:136)
arcadeanalytics-single_1  | 	at org.neo4j.driver.v1.GraphDatabase.driver(GraphDatabase.java:119)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.provider.neo4j3.Neo4jIdUtilsKt.getDriver(Neo4jIdUtils.kt:41)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.provider.neo4j3.Neo4jDataProvider.testConnection(Neo4jDataProvider.kt:144)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.web.rest.DataSourceResource.testDataSource(DataSourceResource.java:143)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.web.rest.DataSourceResource$$FastClassBySpringCGLIB$$89a9850e.invoke(<generated>)
`

I am able to ping the neo4j container from the arcade container and even curl the DB:
`
sudo docker exec -it docker_arcadeanalytics-single_1 /bin/sh
/ # curl http://arcadeanalytics-neo4j:7474
{
  "bolt_routing" : "neo4j://arcadeanalytics-neo4j:7687",
  "transaction" : "http://arcadeanalytics-neo4j:7474/db/{databaseName}/tx",
  "bolt_direct" : "bolt://arcadeanalytics-neo4j:7687",
  "neo4j_version" : "4.0.6",
  "neo4j_edition" : "community"
`

Could there be an issue with neo4j driver in arcade? Any pointers would be greatly appreciated

**Comment by ysruthi** [comment]
I had a chance to debug this, and the SSH private key issue seems to be related to openssh version discrepancy between the arcade docker image and the host where the keys were generated (Mac). I was able to get around the SSH issue by converting the key to PEM format with no passphrase. 
However, I am still getting an error:
`arcadeanalytics-single_1  | 2020-06-25 20:56:34.124 ERROR 1 --- [  XNIO-2 task-9] o.z.p.spring.web.advice.AdviceTrait      : Internal Server Error
arcadeanalytics-single_1  |
arcadeanalytics-single_1  | org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database`

A little bit of googling tells me that the issue could be with using an incompatible Neo4j driver with server. I am using the latest docker image for running Neo4j server, which is 4.0.6 CE. Seems like the Neo4j driver that comes with arcadeanalytics docker image is pretty old, 1.x. This might be causing issues:
https://community.neo4j.com/t/error-when-using-v1-7-x-java-driver-with-neo4j-4-x/13253

Is there a way I can work around this. We would really like to see arcade analytics working with Neo4j. Also, please let me know if you'd rather prefer me posting this to arcadeconnectors repo instead

**Comment by ysruthi** [comment]
I am getting the following error with Memgraph, again from what it seems like driver incompatibility issue with DB. Any help will be greatly appreciated @robfrank 

`arcadeanalytics-single_1  | 2020-06-26 04:17:01.883 ERROR 8 --- [tics-Executor-1] c.a.service.ElasticGraphIndexerService   : error while indexing datasource 1251
arcadeanalytics-single_1  |
arcadeanalytics-single_1  | org.neo4j.driver.v1.exceptions.UntrustedServerException: Server provides no product identifier`

**Comment by arcade-player** [comment]
We support only neo up to 3.5.x.

**Comment by emigre459** [comment]
@arcade-player  Does AA still only support up to Neo4j 3.5.x?
